#server {
#  server_name admin.lmusic.kz www.admin.lmusic.kz;
#  access_log off;
#  return 301 https://admin.lmusic.kz$request_uri;
#}

server {
    listen 80;
    server_name mylara.ru www.mylara.ru;

    root /var/www/html/public;
    index index.php index.html;

    access_log   /proc/self/fd/2;
    error_log    /proc/self/fd/2;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS $http_x_forwarded_proto;
    }

    location ~ /\.ht {
        deny all;
    }
}