services:

  # MariaDB 10.3 с импортом дампа
  mylara_mariadb:
    image: mariadb:10.3
    container_name: mylara_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: mylara
      MYSQL_USER: mylara
      MYSQL_PASSWORD: 5jttBDR5
    volumes:
      - ./_docker/dbconf:/etc/mysql/conf.d
      - ./_docker/data:/var/lib/mysql
      - ./_docker/db_dump/.:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - mylara_net

  # Веб-сервер (Nginx)
  web:
    image: nginx:alpine
    container_name: mylara_web
    ports:
      - "81:80" # Порт 80 на хосте будет перенаправлен на порт 80 в контейнере
    volumes:
      - ./:/var/www/html # Монтируем папку src на хосте в корневую директорию веб-сервера
      - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Конфигурация Nginx
    depends_on:
      - php
      - mylara_mariadb
    networks:
      - mylara_net

  # PHP
  php:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    container_name: mylara_php
    env_file:
      - .env
    volumes:
      - ./:/var/www/html # Монтируем папку src на хосте в корневую директорию PHP
    networks:
      - mylara_net
    depends_on:
      - mylara_mariadb

  composer:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
      target: prebuild  # ← используем стадию, где уже установлен composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "/usr/local/bin/composer" ]
    networks:
      - mylara_net


networks:
  mylara_net:
    driver: bridge
