; php-custom.ini

; Максимальный объём памяти для скрипта
memory_limit = 256M

; Максимальный размер загружаемого файла
upload_max_filesize = 100M

; Максимальный размер POST-данных (должен быть >= upload_max_filesize)
post_max_size = 100M

; Максимальное время выполнения скрипта (в секундах)
max_execution_time = 300

; Максимальное время на получение данных
max_input_time = 300

display_errors = stderr
